---
server:
  host: 0.0.0.0
  port: 9091
  path: authelia

log:
  level: debug

jwt_secret: dr$t%rfEdj*kgfv@hOoi

authentication_backend:
  file:
    path: /config/users_database.yml
    watch: true
    password:
      algorithm: argon2id
      iterations: 3
      memory: 65536
      parallelism: 4
      key_length: 32
      salt_length: 16

access_control:
  default_policy: one_factor

session:
  name: authelia_session
  secret: Hk(jT5FSe$tyHhuYcXer
  expiration: 12h
  inactivity: 2h
  domain: 10.6.0.4

storage:
  encryption_key: 7h^fsd$tGJKutR$%^tdY
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
